import json
from google import genai
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv(override=True)


class JobRequirements(BaseModel):
    required_skills: list[str]
    preferred_skills: list[str]
    education_keywords: list[str]
    certifications: list[str]
    min_experience_years: int
    salary_range: str


# Use the structured output feature of gemini
client = genai.Client()


def generate_requirements(role_title: str) -> JobRequirements:
    prompt = f"""
You are an expert technical HR recruiter.
Define the ideal technical requirements for the position: "{role_title}".
Provide deep, specific, and accurate technical keywords.
- Intern/Fresher roles should focus on fundamentals, basic tools, and languages.
- Junior/Middle should include frameworks, databases, cloud, and standard tools.
- Senior/Expert should include architecture, advanced tools, performance tuning, leadership.
Do not use generic terms like "communication skills". Only technical keywords or specific methodologies (e.g. Agile, Scrum).
Make sure required_skills has 5-10 items and preferred_skills has 5-10 items.
"""
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config={
            "response_mime_type": "application/json",
            "response_schema": JobRequirements,
            "temperature": 0.2,
        },
    )
    return JobRequirements.model_validate_json(response.text)


def main():
    with open("job_requirements_config.json", "r", encoding="utf-8") as f:
        config = json.load(f)

    # To avoid API rate limits on 54 requests, we will process all of them
    # But for a realistic approach without hitting 429, maybe we just batch them
    # Or just sleep. Actually let's try calling it for a few if it works.

    # Wait, the user already generated 54 roles using `expand_levels.py`. Let's just refine them.
    # To avoid rate limits (429), let's generate 5 core roles * 3 levels = 15 roles.
    # No, the user wants all 54.
    # Let's generate a single prompt that asks for an array of all 54 roles? That's too big.
    # Let's just do a loop and sleep 2 seconds.
    import time

    updated_count = 0
    for position, details in config.items():
        # Check if already generated by LLM
        if "skills" in details.get("technical_skills", {}).get("required", {}):
            print(f"Skipping {position} (already generated)...")
            continue

        print(f"Generating for {position}...")
        try:
            req = generate_requirements(position)

            # Update config
            details["technical_skills"] = {
                "required": {"skills": req.required_skills},
                "preferred": {"skills": req.preferred_skills},
                "weight": 50,
            }
            details["experience"]["min_years"] = req.min_experience_years
            details["education"]["preferred_majors"] = req.education_keywords
            details["certifications"]["preferred"] = req.certifications
            details["position_info"]["salary_range"] = req.salary_range

            updated_count += 1
            print(f"Success for {position}. Sleeping to avoid 429 rate limit...")
            time.sleep(15)  # avoid 429
        except Exception as e:
            print(f"Error on {position}: {e}")

    with open("job_requirements_config.json", "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2, ensure_ascii=False)

    print(f"Successfully updated {updated_count} positions.")


if __name__ == "__main__":
    main()
