"""Add interview_questions to ScreeningResult

Revision ID: 0042c88e8eb7
Revises: 4daa9d37ccc8
Create Date: 2026-05-24 09:50:23.929931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0042c88e8eb7"
down_revision: Union[str, Sequence[str], None] = "4daa9d37ccc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "screening_results", sa.Column("interview_questions", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("screening_results", "interview_questions")
    # ### end Alembic commands ###
