"""add interview_questions

Revision ID: c498c4ed1a74
Revises: 0042c88e8eb7
Create Date: 2026-05-24 18:05:44.366367

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c498c4ed1a74"
down_revision: Union[str, Sequence[str], None] = "0042c88e8eb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
